# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\00科莱特\项目\内部管理系统\kltrpa\ui\loginwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(397, 241)
        self.remember_checkbox = QtWidgets.QCheckBox(login_window)
        self.remember_checkbox.setGeometry(QtCore.QRect(40, 160, 151, 19))
        self.remember_checkbox.setObjectName("remember_checkbox")
        self.layoutWidget = QtWidgets.QWidget(login_window)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 190, 301, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.grid = QtWidgets.QGridLayout(self.layoutWidget)
        self.grid.setContentsMargins(0, 0, 0, 0)
        self.grid.setHorizontalSpacing(20)
        self.grid.setVerticalSpacing(10)
        self.grid.setObjectName("grid")
        self.login_button = QtWidgets.QPushButton(self.layoutWidget)
        self.login_button.setStyleSheet("background-color: #82b74b; color: white; border: none; padding: 8px 15px;")
        self.login_button.setObjectName("login_button")
        self.grid.addWidget(self.login_button, 0, 0, 1, 1)
        self.exit_button = QtWidgets.QPushButton(self.layoutWidget)
        self.exit_button.setStyleSheet("background-color: #d54d4d; color: white; border: none; padding: 8px 15px;")
        self.exit_button.setObjectName("exit_button")
        self.grid.addWidget(self.exit_button, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(login_window)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 10, 331, 127))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hbox1_2 = QtWidgets.QHBoxLayout()
        self.hbox1_2.setObjectName("hbox1_2")
        self.server_label = QtWidgets.QLabel(self.layoutWidget1)
        self.server_label.setObjectName("server_label")
        self.hbox1_2.addWidget(self.server_label)
        self.server_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.server_edit.setObjectName("server_edit")
        self.hbox1_2.addWidget(self.server_edit)
        self.verticalLayout.addLayout(self.hbox1_2)
        self.hbox2_2 = QtWidgets.QHBoxLayout()
        self.hbox2_2.setObjectName("hbox2_2")
        self.db_label = QtWidgets.QLabel(self.layoutWidget1)
        self.db_label.setObjectName("db_label")
        self.hbox2_2.addWidget(self.db_label)
        self.db_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.db_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.db_edit.setObjectName("db_edit")
        self.hbox2_2.addWidget(self.db_edit)
        self.verticalLayout.addLayout(self.hbox2_2)
        self.hbox1 = QtWidgets.QHBoxLayout()
        self.hbox1.setObjectName("hbox1")
        self.username_label = QtWidgets.QLabel(self.layoutWidget1)
        self.username_label.setObjectName("username_label")
        self.hbox1.addWidget(self.username_label)
        self.username_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.username_edit.setObjectName("username_edit")
        self.hbox1.addWidget(self.username_edit)
        self.verticalLayout.addLayout(self.hbox1)
        self.hbox2 = QtWidgets.QHBoxLayout()
        self.hbox2.setObjectName("hbox2")
        self.password_label = QtWidgets.QLabel(self.layoutWidget1)
        self.password_label.setObjectName("password_label")
        self.hbox2.addWidget(self.password_label)
        self.password_edit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.hbox2.addWidget(self.password_edit)
        self.verticalLayout.addLayout(self.hbox2)

        self.retranslateUi(login_window)
        self.exit_button.clicked.connect(login_window.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(login_window)
        login_window.setTabOrder(self.username_edit, self.password_edit)
        login_window.setTabOrder(self.password_edit, self.remember_checkbox)
        login_window.setTabOrder(self.remember_checkbox, self.login_button)
        login_window.setTabOrder(self.login_button, self.exit_button)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "登录界面"))
        self.remember_checkbox.setText(_translate("login_window", "记住账号和密码"))
        self.login_button.setText(_translate("login_window", "登录"))
        self.exit_button.setText(_translate("login_window", "退出"))
        self.server_label.setText(_translate("login_window", "域  名："))
        self.db_label.setText(_translate("login_window", "数据库："))
        self.username_label.setText(_translate("login_window", "用户名："))
        self.password_label.setText(_translate("login_window", "密  码："))
