# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\00科莱特\项目\内部管理系统\kltrpa\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(1421, 716)
        self.tabWidget = QtWidgets.QTabWidget(mainwindow)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 1401, 651))
        self.tabWidget.setObjectName("tabWidget")
        self.fetch_result = QtWidgets.QWidget()
        self.fetch_result.setObjectName("fetch_result")
        self.fetch_table = QtWidgets.QTableWidget(self.fetch_result)
        self.fetch_table.setGeometry(QtCore.QRect(10, 10, 1261, 611))
        self.fetch_table.setMinimumSize(QtCore.QSize(971, 0))
        self.fetch_table.setObjectName("fetch_table")
        self.fetch_table.setColumnCount(0)
        self.fetch_table.setRowCount(0)
        self.tabWidget.addTab(self.fetch_result, "")
        self.omo_integrate = QtWidgets.QWidget()
        self.omo_integrate.setObjectName("omo_integrate")
        self.layoutWidget = QtWidgets.QWidget(self.omo_integrate)
        self.layoutWidget.setGeometry(QtCore.QRect(1280, 10, 101, 186))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vbox1 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vbox1.setContentsMargins(0, 0, 0, 0)
        self.vbox1.setSpacing(50)
        self.vbox1.setObjectName("vbox1")
        self.open_excel_button = QtWidgets.QPushButton(self.layoutWidget)
        self.open_excel_button.setObjectName("open_excel_button")
        self.vbox1.addWidget(self.open_excel_button)
        self.update_omo_button = QtWidgets.QPushButton(self.layoutWidget)
        self.update_omo_button.setObjectName("update_omo_button")
        self.vbox1.addWidget(self.update_omo_button)
        self.batch_download_button = QtWidgets.QPushButton(self.layoutWidget)
        self.batch_download_button.setObjectName("batch_download_button")
        self.vbox1.addWidget(self.batch_download_button)
        self.omo_table = QtWidgets.QTableWidget(self.omo_integrate)
        self.omo_table.setGeometry(QtCore.QRect(10, 10, 1261, 611))
        self.omo_table.setMinimumSize(QtCore.QSize(971, 0))
        self.omo_table.setRowCount(0)
        self.omo_table.setColumnCount(0)
        self.omo_table.setObjectName("omo_table")
        self.tabWidget.addTab(self.omo_integrate, "")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.log_textedit = QtWidgets.QTextEdit(self.log)
        self.log_textedit.setEnabled(True)
        self.log_textedit.setGeometry(QtCore.QRect(10, 10, 1071, 571))
        self.log_textedit.setReadOnly(True)
        self.log_textedit.setObjectName("log_textedit")
        self.tabWidget.addTab(self.log, "")
        self.layoutWidget_2 = QtWidgets.QWidget(mainwindow)
        self.layoutWidget_2.setGeometry(QtCore.QRect(420, 10, 371, 33))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(80)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connect_zhilian_button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.connect_zhilian_button.setMinimumSize(QtCore.QSize(0, 0))
        self.connect_zhilian_button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.connect_zhilian_button.setBaseSize(QtCore.QSize(0, 0))
        self.connect_zhilian_button.setStyleSheet("background-color: #82b74b; color: white; border: none; padding: 8px 15px;")
        self.connect_zhilian_button.setObjectName("connect_zhilian_button")
        self.horizontalLayout.addWidget(self.connect_zhilian_button)
        self.fetch_info_button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.fetch_info_button.setStyleSheet("background-color: #82b74b; color: white; border: none; padding: 8px 15px;")
        self.fetch_info_button.setObjectName("fetch_info_button")
        self.horizontalLayout.addWidget(self.fetch_info_button)

        self.retranslateUi(mainwindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "智联简历处理"))
        self.fetch_table.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fetch_result), _translate("mainwindow", "抓取结果"))
        self.open_excel_button.setText(_translate("mainwindow", "打开文件"))
        self.update_omo_button.setText(_translate("mainwindow", "更新到OMO"))
        self.batch_download_button.setText(_translate("mainwindow", "批量简历下载"))
        self.omo_table.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.omo_integrate), _translate("mainwindow", "OMO集成"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log), _translate("mainwindow", "日志"))
        self.connect_zhilian_button.setText(_translate("mainwindow", "连接智联"))
        self.fetch_info_button.setText(_translate("mainwindow", "批量打招呼并抓取信息"))
